### ISSUE TITLE
建议添加简历照片，和多设计几个简历主题，增加外观的自定义性

### ISSUE THREAD

**Issue by xinjiajuan** [YunYouJun/web-resume#2]
亲爱的君君，简历中的照片是很重要的一个内容，建议君君加上哦
另外建议君君给简历做好美化，给简历万里挑一的感觉哦。😚😚

**Comment by YunYouJun** [comment]
更新一下目前的支持情况：

- 已支持简历照片：标准 JSON Resume 使用 `basics.image`，旧版 YAML 使用 `basics.avatar`，填写照片地址即可。
- 目前提供清晰经典、紧凑单页、专业侧栏三种模板，可通过 **视图 → 模板** 或模板库切换。
- 本次 #16 已合并到 main，补齐了照片布局中的一级标题和图片替代文本，并在三个浏览器中验证了三种模板的照片加载；使用文档也增加了照片示例和模板说明。

例如：
```yaml
basics:
  name: 林知行
  image: https://example.com/photo.jpg
```

照片和多模板能力已有覆盖；更细粒度的外观自定义仍可继续推进，因此暂时保留此 issue。后续可以在这里补充具体希望调整的配色、字体或布局选项。
